version: 1.0
stages:
- StageOne
jobs:
  fdasfads:
    description: ''
    typ
    e: source-checkout
    stage: StageOne
    timeout: 30
    priority: major
    parameters:
      branch: $CM_PIPELINE_ID
